baseURL: https://sdalwani.netlify.app/
languageCode: en-us
title: Soham's Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore more
    subtitle: |-
     Learn about me, my cocker spaniel, and my attempts at using R
    title: Hello everyone, my name is Soham 
  blog: {}
  contact: 
    address:
      - city: London, L12 G43
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear all
    buttonSend: Send 
    email:
      - email: sdalwani.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+91) 9958817567
        title: Phone (India)
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Soham Dalwani
    enable: yes
    quicklinks:
      - alt: HTML5 UP
#        text: 'Design: '
#        url: https://www.html5up.net/
    social:
        #icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/soham.dalwani/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/sohamdalwani/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/sd6599/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sohamdalwani/
  image: ''
  name: Your name
  navigation:
    links:
      - name: About me
        url: '#'
      - name: Posts
        url: blogs
    button1:
      - name: Read about me
        url: blogs
    button2:
      - name: Back to home
        url: '#'
#      - name: Generic Blog
 #       url: blogs/ipsum
  #    - name: Elements
   #     url: elements.html
    menu: Explore
#    subtitle: About me
    title: Soham Dalwani
  tiles:
    enable: yes
    showcase:
      - image: Santi.JPG
        subtitle: Put whatever assignment 1 is
        title: Assignment 1
        url: blogs/assignment1
      - image: pic02.jpg
        subtitle: Describe whatever 2 is
        title: Assignment 2
        url: blogs/assignment2
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
